#!/usr/bin/perl

use strict;
use warnings;
use diagnostics;
use List::Util qw(minstr);


use v5.32;

say "Enter a couple of numbers";

my @numbers;
while (my $input = <STDIN>) {
    chomp($input);

    last if $input eq '';  # Stop if an empty line is entered

    if ($input =~ /^-?\d+(\.\d+)?$/) {
        push @numbers, $input;
    } else {
        print "Invalid input. Please enter a valid number.\n";
    }
}

if (@numbers) {
    my $min = $numbers[0];
    my $max = $numbers[0];
    my $sum = 0;

    foreach my $num (@numbers) {
        $min = $num if $num < $min;
        $max = $num if $num > $max;
        $sum += $num;
    }

    my $mean = $sum / scalar(@numbers);

        @numbers = sort { $a <=> $b } @numbers;  # Sorting the numbers in ascending order
    my $median;
    my $num_count = scalar(@numbers);

    if ($num_count % 2 == 0) {
        my $middle_index = $num_count / 2;
        $median = ($numbers[$middle_index - 1] + $numbers[$middle_index]) / 2;
    } else {
        my $middle_index = int($num_count / 2);
        $median = $numbers[$middle_index];
    }

    print "Minmal value is $min \nMaximal value is $max\n";
    say "Mean value is $mean";
    say "Median value is $median";
}