#!/usr/bin/perl

#Use statments to make sure proper Perl is writen and we are informed of bad uses or errors
use strict;
use warnings;
use diagnostics;
use List::Util qw(shuffle);

#Version specification to maximise compatibility
use v5.32;

# Read the input file containing the master exam
my $input_file = '0_ENTRANCE_EXAM_MASTER_';
open my $fh_in, '<', $input_file or die "Could not open $input_file: $!";

# Open the output file to write modified content
my $output_file = 'modified_exam.txt';
open my $fh_out, '>', $output_file or die "Could not open $output_file: $!";

# Initialize variables to hold questions and answers
my @questions;
my %answer_sets; # Hash to store answer sets for each question

# Process each line in the input file
while (my $line = <$fh_in>) {
    chomp $line;

    # Detect questions and answer sets
    if ($line =~ /^(\d+\.\s+.+)$/) {
        push @questions, $1;
        $answer_sets{$1} = []; # Initialize answer set array for the question
    } elsif ($line =~ /^\s*\[.\]\s+(.+)$/ && @questions) {
        push @{$answer_sets{$questions[-1]}}, $1; # Add answer to the last question encountered
    }
}

# Close the input file
close $fh_in;

# Write the modified content to the output file
for my $i (0..$#questions) {
    print $fh_out "________________________________________________________________________________\n\n";
    print $fh_out "$questions[$i]\n\n";

    my @shuffled_answers = shuffle @{$answer_sets{$questions[$i]}};
    for my $j (0..$#shuffled_answers) {
        print $fh_out "    [ ] $shuffled_answers[$j]\n";
    }

    print $fh_out "\n";
}

# Close the output file
close $fh_out;

print "Modified exam content written to $output_file\n";