#!/usr/bin/perl

use strict;
use warnings;
use diagnostics;

use feature 'say';

use feature "switch";

use v5.16;

print "Hello world\n";

my $name = 'Trito';

my ($age, $street) = (22, '115 rue de hésingue');

my $my_info = "$name lives on \"$street\"\n";

$my_info = qq{$name lives on "$street"\n};

print "$my_info";